/**
 * Arena sandbox helper: recreates the gitignored env files after a sandbox
 * reset (backend/.env via the project's own setup script, then sandbox
 * overrides; frontend/.env.local with the live preview origin).
 * Idempotent — run any time.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sandboxId = process.env.E2B_SANDBOX_ID;
if (!sandboxId) {
  console.error('[envs] E2B_SANDBOX_ID not set — cannot compute the preview origin.');
  process.exit(1);
}
const preview = (port) => `https://${port}-${sandboxId}.e2b.app`;

// --- backend/.env -----------------------------------------------------------
const backendEnv = path.join(root, 'backend', '.env');
if (!fs.existsSync(backendEnv)) {
  console.log('[envs] creating backend/.env via scripts/setup-env.mjs…');
  execFileSync('node', ['scripts/setup-env.mjs'], { cwd: path.join(root, 'backend'), stdio: 'inherit' });
}
let env = fs.readFileSync(backendEnv, 'utf8');
const setVar = (key, value) => {
  const re = new RegExp(`^${key}=.*$`, 'm');
  if (re.test(env)) env = env.replace(re, `${key}=${value}`);
  else env += `\n${key}=${value}`;
};
setVar('DATABASE_URL', 'postgresql://postgres@127.0.0.1:54329/postgres?schema=public');
setVar('CORS_ORIGINS', `http://localhost:5173,http://localhost:3001,${preview(3000)},${preview(3001)}`);
setVar('FRONTEND_BASE_URL', preview(3001));
setVar('OTP_FIXED_CODE', '123456');
fs.writeFileSync(backendEnv, env);
console.log('[envs] backend/.env ready (embedded postgres + preview origins + fixed OTP)');

// --- frontend/.env.local ------------------------------------------------------
const frontEnv = path.join(root, 'frontend', '.env.local');
const frontContent = `# --- Arena sandbox preview wiring (auto-generated by sandbox/envs.mjs) ---
NEXT_PUBLIC_API_URL=${preview(3001)}/api/v1
API_PROXY_TARGET=http://127.0.0.1:3000
API_BASE_URL=http://127.0.0.1:3000/api/v1
`;
fs.writeFileSync(frontEnv, frontContent);
console.log('[envs] frontend/.env.local ready');
